export const User = [
    {
        _id :"1",
        name : "user1",
        email : "user1@gmail.com",
        password : "1234",
        isAdmin : false,
    },
    {
        _id :"2",
        name : "user2",
        email : "user2@gmail.com",
        password : "1234",
        isAdmin : false,
    },
    {
        _id :"3",
        name : "user3",
        email : "user3@gmail.com",
        password : "1234",
        isAdmin : false,
    },
]

export const Course = [
    {
        name : "Web development",
        quantity : 1,
        category : "Web",
        img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
        description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
        totalsell: 22,
        rating : 3.5,
        price : 56,
    },
    {
        name : "Apps development",
        quantity : 1,
        category : "Apps",
        img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
        description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
        totalsell: 22,
        rating : 4.5,
        price : 46,
    },
    {
        name : "Graphics Design",
        quantity : 1,
        category : "Graphicsdesign",
        img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
        description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
        totalsell: 22,
        rating : 2.5,
        price : 76,
    },
    {
        name : "Graphics Design",
        quantity : 1,
        category : "Graphicsdesign",
        img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
        description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
        totalsell: 22,
        rating : 2.5,
        price : 76,
    },
    {
        name : "Graphics Design",
        quantity : 1,
        category : "Graphicsdesign",
        img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
        description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
        totalsell: 22,
        rating : 2.5,
        price : 76,
    },
    {
        name : "Graphics Design",
        quantity : 1,
        category : "Graphicsdesign",
        img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
        description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
        totalsell: 22,
        rating : 2.5,
        price : 76,
    },
]

export const OrderItem = [
    {
        _id : "0",
        userid : "1",
        orderitem : [
            {
                _id : "27",
                name : "Graphics Design",
                quantity : 1,
                category : "Graphicsdesign",
                img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
                description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
                totalsell: 22,
                rating : 2.5,
                price : 76,
            },
            {
                _id : "25",
                name : "Apps development",
                quantity : 1,
                category : "Apps",
                img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
                description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
                totalsell: 22,
                rating : 4.5,
                price : 46,
            },
        ],
        paymentMethod : "paypal",
        itemprice : 122,
        totalPrice : 130,
        isPaid : false,
        paidAt : new Date(),
        isSelled : false,
        sellAt : new Date(),
    },
    {
        _id : "1",
        userid : "2",
        orderitem : [
            {
                _id : "27",
                name : "Graphics Design",
                quantity : 1,
                category : "Graphicsdesign",
                img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
                description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
                totalsell: 22,
                rating : 2.5,
                price : 76,
            },
            {
                _id : "25",
                name : "Apps development",
                quantity : 1,
                category : "Apps",
                img : "https://res.cloudinary.com/image-hosting-api/image/upload/v1653136975/pexels-photo-5632405_cxucw4.jpg",
                description: "Complete coverage of HTML, CSS, Javascript while you Earn Four Respected Certifications",
                totalsell: 22,
                rating : 4.5,
                price : 46,
            },
        ],
        paymentMethod : "paypal",
        itemprice : 122,
        totalPrice : 130,
        isPaid : false,
        paidAt : new Date(),
        isSelled : false,
        sellAt : new Date(),
    }
]